### ISSUE TITLE
Doesn't run on clean Win 7 install

### ISSUE THREAD

**Issue by billw2012** [caveman2cosmos/C2C-GitVersion#1]
```appveyor.yml-c2c-version:40.0.0
System.MissingMethodException: Method not found: 'System.String System.String.Format(System.IFormatProvider, System.Stri
ng, System.Object)'.
   at LibGit2Sharp.Core.StrictFilePathMarshaler.MarshalManagedToNative(Object managedObj)
   at System.StubHelpers.MngdRefCustomMarshaler.ConvertContentsToNative(IntPtr pMarshalState, Object& pManagedHome, IntP
tr pNativeHome)
   at LibGit2Sharp.Core.NativeMethods.git_repository_open(git_repository*& repository, FilePath path)
   at LibGit2Sharp.Core.Proxy.git_repository_open(String path)
   at LibGit2Sharp.Repository..ctor(String path, RepositoryOptions options, RepositoryRequiredParameter requiredParamete
r)
   at GitVersion.Program.Main()
NMAKE : fatal error U1077: '"..\\Tools\C2C-GitVersion.exe"' : return code '0xffffffff'
Stop.

Microsoft (R) Program Maintenance Utility Version 7.10.3077```

**Comment by ghost** [comment]
System.String.Format(System.IFormatProvider, System.Stri
ng, System.Object) only exists starting with .net4.5 or maybe even 4.6. That clean win7 install probably only has .net 3.5 installed.

**Comment by ghost** [comment]
Maybe include the [.NET 4.8 Web Installer](http://go.microsoft.com/fwlink/?LinkId=2085155) into the Caveman2Cosmos dev setup.

**Comment by billw2012** [comment]
I put in a PR instead that downgrades it to work with 4.5.  Although 4.5 still isn't included as default, it will be automatically installed by one of our tools (can't remember which one). Weird that this tool doesn't automatically try to install 4.7 or whatever version it needs? Maybe it is a setting somewhere.

**Comment by ghost** [comment]
Did you install any kind of software in that clean windows 7 or did maybe the windows 7 you installed already include software or the .net 4.5?
That would explain it.

**Comment by billw2012** [comment]
Yeah 4.5 gets automatically installed by something. But I'm not worried about this we can leave it as is I think, certainly I'm bored with writing installer scripts now!

**Comment by ghost** [comment]
I add the .net 4.8 web installer to the dev setup.
